spring:
  application:
    name: genesis
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/genesis
    username: fekazo
    password: Halo1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8080
  error:
    include-stacktrace: never